//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModLoader.GameSpecific.Rayman3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rayman3_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rayman3_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModLoader.GameSpecific.Rayman3.Rayman3_Text", typeof(Rayman3_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rayman 3: Hoodlum Havoc.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game Into 2D Nightmare.
        /// </summary>
        internal static string Mod_NewGameNightmare {
            get {
                return ResourceManager.GetString("Mod_NewGameNightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting a new game places you in the 2D Nightmare level..
        /// </summary>
        internal static string Mod_NewGameNightmareDesc {
            get {
                return ResourceManager.GetString("Mod_NewGameNightmareDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Intro Video.
        /// </summary>
        internal static string Mod_RemoveIntroVideo {
            get {
                return ResourceManager.GetString("Mod_RemoveIntroVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the video that plays before the main menu..
        /// </summary>
        internal static string Mod_RemoveIntroVideoDesc {
            get {
                return ResourceManager.GetString("Mod_RemoveIntroVideoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Level Order (Any amount of Levels).
        /// </summary>
        internal static string Rand_LevelOrder {
            get {
                return ResourceManager.GetString("Rand_LevelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Level Order (All Levels).
        /// </summary>
        internal static string Rand_LevelOrder2 {
            get {
                return ResourceManager.GetString("Rand_LevelOrder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels are shuffled around. The final boss is still the last level to play (followed by credits).
        /// </summary>
        internal static string Rand_LevelOrder2Desc {
            get {
                return ResourceManager.GetString("Rand_LevelOrder2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels are shuffled around. The final boss may appear after any amount of levels (followed by credits).
        /// </summary>
        internal static string Rand_LevelOrderDesc {
            get {
                return ResourceManager.GetString("Rand_LevelOrderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Outfit Visuals.
        /// </summary>
        internal static string Rand_OutfitColors {
            get {
                return ResourceManager.GetString("Rand_OutfitColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The textures for outfits are shuffled around..
        /// </summary>
        internal static string Rand_OutfitColorsDesc {
            get {
                return ResourceManager.GetString("Rand_OutfitColorsDesc", resourceCulture);
            }
        }
    }
}
