//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModLoader.GameSpecific.CrashTTR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CTTR_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CTTR_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModLoader.GameSpecific.CrashTTR.CTTR_Text", typeof(CTTR_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIs by NeoKesha and BetaM.
        /// </summary>
        internal static string API_Credit {
            get {
                return ResourceManager.GetString("API_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Tag Team Racing.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Sequence Breaks.
        /// </summary>
        internal static string Mod_PreventSkips {
            get {
                return ResourceManager.GetString("Mod_PreventSkips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone transitions in the Midway will not work without using a gem key first. Getting gem keys will not work without unlocking them first..
        /// </summary>
        internal static string Mod_PreventSkipsDesc {
            get {
                return ResourceManager.GetString("Mod_PreventSkipsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race Laps.
        /// </summary>
        internal static string RaceLaps {
            get {
                return ResourceManager.GetString("RaceLaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the lap count in the Race gamemode..
        /// </summary>
        internal static string RaceLapsDesc {
            get {
                return ResourceManager.GetString("RaceLapsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Minigames.
        /// </summary>
        internal static string Rand_Minigames {
            get {
                return ResourceManager.GetString("Rand_Minigames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minigame unlocks are shuffled around..
        /// </summary>
        internal static string Rand_MinigamesDesc {
            get {
                return ResourceManager.GetString("Rand_MinigamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Platforming Character (Unstable).
        /// </summary>
        internal static string Rand_PlatformingCharacter {
            get {
                return ResourceManager.GetString("Rand_PlatformingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character you platform as in the park is randomized. The game may crash after a few races..
        /// </summary>
        internal static string Rand_PlatformingCharacterDesc {
            get {
                return ResourceManager.GetString("Rand_PlatformingCharacterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Race Laps.
        /// </summary>
        internal static string Rand_RaceLaps {
            get {
                return ResourceManager.GetString("Rand_RaceLaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lap count in each track is randomized..
        /// </summary>
        internal static string Rand_RaceLapsDesc {
            get {
                return ResourceManager.GetString("Rand_RaceLapsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Track Entrances.
        /// </summary>
        internal static string Rand_TrackEntrances {
            get {
                return ResourceManager.GetString("Rand_TrackEntrances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track entrances are shuffled around..
        /// </summary>
        internal static string Rand_TrackEntrancesDesc {
            get {
                return ResourceManager.GetString("Rand_TrackEntrancesDesc", resourceCulture);
            }
        }
    }
}
