//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModLoader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModLoader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.0
        ///
        ///General:
        ///- PS2 ROM building is now supported internally (Thanks to Smartkin). Folder mode is now supported.  
        ///- Options are now handled the same as Mod Menu properties allowing them to be set by Mod Crates and enabling variations and choices like difficulty settings in Mod Menus.  
        ///
        ///Crash Twinsanity:
        ///- New feature: Classic Health
        ///- New feature: Classic Explosion Damage
        ///- Fixed default values for character health
        ///
        ///1.2.1
        ///
        ///Crash Twinsanity:
        ///- Fixed processing errors in some versions of the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cml_icon {
            get {
                object obj = ResourceManager.GetObject("cml_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate Mod Loader Supported Games
        ///  
        ///Crash Nitro Kart
        ///Supported: All PS2 versions (.ISO format), All GC versions (.ISO format), All XBOX versions (.ISO format)  
        ///Mod abbreviation: CrashNK  
        ///Mod Menu enabled.
        ///Mod layers: 1 - ASSETS.GOB contents
        ///Tools/API by BetaM, ManDude and eezstreet.  
        ///Features:  
        ///- Randomize Adventure  
        ///- Randomize Character Stats
        ///- Randomize Kart Stats
        ///- Randomize Powerup Effects
        ///- Randomize Drivers  
        ///- Randomize Karts  
        ///- Disable Fadeout/Flash Overlay
        ///- Disable Unlock Po [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate Mod Loader v1.3.0
        ///The all-in-one Randomizer and Mod Loader for console games.  
        ///It detects, extracts, modifies and rebuilds disc image files and directories in an easy to setup way.  
        ///In addition, it allows for standalone &quot;Mod Crates&quot; to be installed seamlessly into games.
        ///
        ///Website: https://github.com/TheBetaM/CrateModLoader/
        ///
        ///Contributors:
        ///
        ///-BetaM (https://www.youtube.com/BetaM) (Creator) (Support development: https://ko-fi.com/thebetam)
        ///-ManDude (https://github.com/ManDude) 
        ///
        ///Mod Crates        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Readme {
            get {
                return ResourceManager.GetString("Readme", resourceCulture);
            }
        }
    }
}
