//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModLoader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModLoader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.0
        ///
        ///General:
        ///- PS2 building is now internally supported (Thanks to Smartkin). Folder mode is now supported.  
        ///
        ///1.2.1
        ///
        ///Crash Twinsanity:
        ///- Fixed processing errors in some versions of the game
        ///
        ///1.2.0
        ///
        ///General:  
        ///- Added support for Xbox 360 ROMs and directories (can only output to folder).  
        ///- Improved Xbox ROM detection speed.  
        ///- Added a warning if the program fails to verify a Mod Crate.  
        ///- Console/Region specific options will not appear on unsupported versions anymore.  
        ///- The window  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cml_icon {
            get {
                object obj = ResourceManager.GetObject("cml_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate Mod Loader Supported Games
        ///  
        ///Crash Nitro Kart
        ///Supported: All PS2 versions (.ISO format), All GC versions (.ISO format), All XBOX versions (.ISO format)  
        ///Mod abbreviation: CrashNK  
        ///Mod Menu enabled.
        ///Mod layers: 1 - ASSETS.GOB contents
        ///Tools/API by BetaM, ManDude and eezstreet.  
        ///Features:  
        ///- Randomize Adventure  
        ///- Randomize Character Stats
        ///- Randomize Kart Stats
        ///- Randomize Powerup Effects
        ///- Randomize Drivers  
        ///- Randomize Karts  
        ///- Disable Fadeout/Flash Overlay
        ///- Disable Unlock Po [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crash1 {
            get {
                object obj = ResourceManager.GetObject("icon_crash1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crash2 {
            get {
                object obj = ResourceManager.GetObject("icon_crash2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crash3 {
            get {
                object obj = ResourceManager.GetObject("icon_crash3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crashbash {
            get {
                object obj = ResourceManager.GetObject("icon_crashbash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crashmom {
            get {
                object obj = ResourceManager.GetObject("icon_crashmom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crashnk {
            get {
                object obj = ResourceManager.GetObject("icon_crashnk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crashtitans {
            get {
                object obj = ResourceManager.GetObject("icon_crashtitans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crashtr {
            get {
                object obj = ResourceManager.GetObject("icon_crashtr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crashts {
            get {
                object obj = ResourceManager.GetObject("icon_crashts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crashttr {
            get {
                object obj = ResourceManager.GetObject("icon_crashttr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_crashtwoc {
            get {
                object obj = ResourceManager.GetObject("icon_crashtwoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_ray3 {
            get {
                object obj = ResourceManager.GetObject("icon_ray3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate Mod Loader v1.3.0
        ///The all-in-one Randomizer and Mod Loader for console games.  
        ///It detects, extracts, modifies and rebuilds disc image files and directories in an easy to setup way.  
        ///In addition, it allows for standalone &quot;Mod Crates&quot; to be installed seamlessly into games.
        ///
        ///Website: https://github.com/TheBetaM/CrateModLoader/
        ///
        ///Check the included Games.txt for a list of supported games and features.  
        ///
        ///Mod Crates
        ///
        ///Place Mod Crates in the &quot;Mods&quot; folder for them to appear in the list.
        ///An exam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Readme {
            get {
                return ResourceManager.GetString("Readme", resourceCulture);
            }
        }
    }
}
