//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModLoader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModLoader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.0
        ///
        ///General
        ///- PS2 DVD, PSP and Folder mode extraction step is now multithreaded
        ///- Modding step is now multithreaded (for most games)
        ///- Much faster detection for PS1 and PS2 CD games  
        ///- PS1 and PS2 CD games now use mkpsxiso for rebuilding, fixing various sound/movie issues and improving compatibility
        ///- Added support for DS and 3DS games
        ///- Preloading is now multithreaded and combined with the main process (no longer needs to extract again after clicking Start)
        ///- Every randomizer is now handled in [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cml_icon {
            get {
                object obj = ResourceManager.GetObject("cml_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate Mod Loader Supported Games
        ///  
        ///Crash Nitro Kart
        ///Supported: All PS2 versions (.ISO format), All GC versions (.ISO format), All XBOX versions (.ISO format)  
        ///Recommended: PS2
        ///Tools/API by BetaM, ManDude and eezstreet.  
        ///Version and seed visible in the Credits screen.
        ///Features include:  
        ///- Randomize Adventure  
        ///- Randomize Characters/Karts and their stats
        ///- Disable Fadeout/Flashing Overlay
        ///And more! Aswell as additional features in Mod Menu+!
        ///  
        ///Crash Twinsanity
        ///Supported: All PS2 versions ( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate Mod Loader v1.4.0
        ///The all-in-one Randomizer and Mod Loader for console games.  
        ///It detects, extracts, modifies and rebuilds disc image files and directories in an easy to setup way.  
        ///In addition, it allows for standalone &quot;Mod Crates&quot; to be installed seamlessly into games.
        ///
        ///Website: https://github.com/TheBetaM/CrateModLoader/
        ///
        ///Contributors:
        ///
        ///-BetaM (https://www.youtube.com/BetaM) (Creator) (Support development: https://ko-fi.com/thebetam)
        ///-ManDude (https://github.com/ManDude) 
        ///
        ///Mod Crates        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Readme {
            get {
                return ResourceManager.GetString("Readme", resourceCulture);
            }
        }
    }
}
