//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModGames.GameSpecific.Crash2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Crash2_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Crash2_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModGames.GameSpecific.Crash2.Crash2_Text", typeof(Crash2_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Bandicoot 2: Cortex Strikes Back.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backwards Levels (Beta).
        /// </summary>
        internal static string Mod_BackwardsLevels {
            get {
                return ResourceManager.GetString("Mod_BackwardsLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most levels start at the end and end at the start. There are minimal design changes to ensure levels are beatable. The game is 100% completable. (Jet board levels are onfoot).
        /// </summary>
        internal static string Mod_BackwardsLevelsDesc {
            get {
                return ResourceManager.GetString("Mod_BackwardsLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Crates Are Invisible.
        /// </summary>
        internal static string Mod_InvisibleCrates {
            get {
                return ResourceManager.GetString("Mod_InvisibleCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All crates are invisible until you touch them..
        /// </summary>
        internal static string Mod_InvisibleCratesDesc {
            get {
                return ResourceManager.GetString("Mod_InvisibleCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Enemies Are Random Crates (Beta).
        /// </summary>
        internal static string Rand_AllEnemiesCrates {
            get {
                return ResourceManager.GetString("Rand_AllEnemiesCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All enemies are turned into random crates in each level. The box counter is adjusted accordingly..
        /// </summary>
        internal static string Rand_AllEnemiesCratesDesc {
            get {
                return ResourceManager.GetString("Rand_AllEnemiesCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Boss Levels.
        /// </summary>
        internal static string Rand_BossLevels {
            get {
                return ResourceManager.GetString("Rand_BossLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss patterns in 4 levels are randomized. (Ripper Roo/Komodo Bros./Tiny Tiger/N. Gin).
        /// </summary>
        internal static string Rand_BossLevelsDesc {
            get {
                return ResourceManager.GetString("Rand_BossLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Crates Are Invisible.
        /// </summary>
        internal static string Rand_InvisibleCrates {
            get {
                return ResourceManager.GetString("Rand_InvisibleCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random crates are invisible until you touch them..
        /// </summary>
        internal static string Rand_InvisibleCratesDesc {
            get {
                return ResourceManager.GetString("Rand_InvisibleCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Warp Room Exits.
        /// </summary>
        internal static string Rand_WarpRoom {
            get {
                return ResourceManager.GetString("Rand_WarpRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Warp Room exits and the new game spawn are shuffled around..
        /// </summary>
        internal static string Rand_WarpRoomDesc {
            get {
                return ResourceManager.GetString("Rand_WarpRoomDesc", resourceCulture);
            }
        }
    }
}
