//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModGames.GameSpecific.Crash3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Crash3_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Crash3_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModGames.GameSpecific.Crash3.Crash3_Text", typeof(Crash3_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Bandicoot: WARPED.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backwards Levels (Beta).
        /// </summary>
        internal static string Mod_BackwardsLevels {
            get {
                return ResourceManager.GetString("Mod_BackwardsLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most levels start at the end and end at the start. There are minimal design changes to ensure levels are beatable. The game is NOT 105% completable..
        /// </summary>
        internal static string Mod_BackwardsLevelsDesc {
            get {
                return ResourceManager.GetString("Mod_BackwardsLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Enemies Are Random Crates (Beta).
        /// </summary>
        internal static string Mod_EnemyCrates {
            get {
                return ResourceManager.GetString("Mod_EnemyCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All enemies and hazards are turned into random crates in each level. The box counter is adjusted accordingly..
        /// </summary>
        internal static string Mod_EnemyCratesDesc {
            get {
                return ResourceManager.GetString("Mod_EnemyCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Warp Room Barriers.
        /// </summary>
        internal static string Mod_RemoveWarpRoomWalls {
            get {
                return ResourceManager.GetString("Mod_RemoveWarpRoomWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all barriers in the Warp Room, allowing you to enter warp rooms early. Stepping on a button from a later hub grants powerups from the previous hubs..
        /// </summary>
        internal static string Mod_RemoveWarpRoomWallsDesc {
            get {
                return ResourceManager.GetString("Mod_RemoveWarpRoomWallsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Levels Are Backwards.
        /// </summary>
        internal static string Rand_BackwardsLevels {
            get {
                return ResourceManager.GetString("Rand_BackwardsLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any supported level has a random chance of being backwards. The game is NOT 105% completable..
        /// </summary>
        internal static string Rand_BackwardsLevelsDesc {
            get {
                return ResourceManager.GetString("Rand_BackwardsLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Biplane Levels.
        /// </summary>
        internal static string Rand_FlyingLevels {
            get {
                return ResourceManager.GetString("Rand_FlyingLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels featuring the biplane (17, 24, 28) have randomized paths, spawns and other factors..
        /// </summary>
        internal static string Rand_FlyingLevelsDesc {
            get {
                return ResourceManager.GetString("Rand_FlyingLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Warp Room.
        /// </summary>
        internal static string Rand_WarpRoom {
            get {
                return ResourceManager.GetString("Rand_WarpRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp Room barriers and buttons are shuffled around..
        /// </summary>
        internal static string Rand_WarpRoomDesc {
            get {
                return ResourceManager.GetString("Rand_WarpRoomDesc", resourceCulture);
            }
        }
    }
}
