//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModGames.GameSpecific.Crash1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Crash1_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Crash1_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModGames.GameSpecific.Crash1.Crash1_Text", typeof(Crash1_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Bandicoot.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Crates Are Wumpa.
        /// </summary>
        internal static string Mod_AllCratesWumpa {
            get {
                return ResourceManager.GetString("Mod_AllCratesWumpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All regular crates are replaced with Wumpa fruit. (Cannot earn any gems).
        /// </summary>
        internal static string Mod_AllCratesWumpaDesc {
            get {
                return ResourceManager.GetString("Mod_AllCratesWumpaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backwards Hog Levels (Very Hard!).
        /// </summary>
        internal static string Mod_BackwardsHogLevels {
            get {
                return ResourceManager.GetString("Mod_BackwardsHogLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Hog levels start at the end and end at the start. Not recommended for casual play, races or speedruns as it is very difficult..
        /// </summary>
        internal static string Mod_BackwardsHogLevelsDesc {
            get {
                return ResourceManager.GetString("Mod_BackwardsHogLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backwards Levels.
        /// </summary>
        internal static string Mod_BackwardsLevels {
            get {
                return ResourceManager.GetString("Mod_BackwardsLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All onfoot levels start at the end and end at the start. There are minimal design changes to ensure levels are beatable. The game is 100% completable..
        /// </summary>
        internal static string Mod_BackwardsLevelsDesc {
            get {
                return ResourceManager.GetString("Mod_BackwardsLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Unused Enemies.
        /// </summary>
        internal static string Mod_EnableDog {
            get {
                return ResourceManager.GetString("Mod_EnableDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables unused enemies in &quot;Heavy Machinery&quot;..
        /// </summary>
        internal static string Mod_EnableDogDesc {
            get {
                return ResourceManager.GetString("Mod_EnableDogDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Crates Are Invisible.
        /// </summary>
        internal static string Mod_InvisibleCrates {
            get {
                return ResourceManager.GetString("Mod_InvisibleCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All crates are invisible until you attack or jump on them..
        /// </summary>
        internal static string Mod_InvisibleCratesDesc {
            get {
                return ResourceManager.GetString("Mod_InvisibleCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Levels Are Backwards.
        /// </summary>
        internal static string Rand_BackwardsLevels {
            get {
                return ResourceManager.GetString("Rand_BackwardsLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any level has a random chance of being backwards. Does not include Hog levels..
        /// </summary>
        internal static string Rand_BackwardsLevelsDesc {
            get {
                return ResourceManager.GetString("Rand_BackwardsLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Boss Levels.
        /// </summary>
        internal static string Rand_BossLevels {
            get {
                return ResourceManager.GetString("Rand_BossLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss patterns in 3 levels are randomized. (Ripper Roo/Pinstripe/N. Cortex).
        /// </summary>
        internal static string Rand_BossLevelsDesc {
            get {
                return ResourceManager.GetString("Rand_BossLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Camera Field-Of-View.
        /// </summary>
        internal static string Rand_CameraFOV {
            get {
                return ResourceManager.GetString("Rand_CameraFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance between the camera and the player is randomized..
        /// </summary>
        internal static string Rand_CameraFOVDesc {
            get {
                return ResourceManager.GetString("Rand_CameraFOVDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Crates Are Invisible.
        /// </summary>
        internal static string Rand_InvisibleCrates {
            get {
                return ResourceManager.GetString("Rand_InvisibleCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random crates are invisible until you attack or jump on them..
        /// </summary>
        internal static string Rand_InvisibleCratesDesc {
            get {
                return ResourceManager.GetString("Rand_InvisibleCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Lighting Color.
        /// </summary>
        internal static string Rand_LightCol {
            get {
                return ResourceManager.GetString("Rand_LightCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the default lighting is randomized..
        /// </summary>
        internal static string Rand_LightColDesc {
            get {
                return ResourceManager.GetString("Rand_LightColDesc", resourceCulture);
            }
        }
    }
}
