//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModGames.GameSpecific.Crash1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrashTri_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrashTri_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModGames.GameSpecific.Crash1.CrashTri_Text", typeof(CrashTri_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API by chekwob and ManDude.
        /// </summary>
        internal static string API_Credit {
            get {
                return ResourceManager.GetString("API_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Crates Are Blank.
        /// </summary>
        internal static string Mod_AllCratesBlank {
            get {
                return ResourceManager.GetString("Mod_AllCratesBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All regular crates are replaced with Blank ones..
        /// </summary>
        internal static string Mod_AllCratesBlankDesc {
            get {
                return ResourceManager.GetString("Mod_AllCratesBlankDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Crates Are Wumpa.
        /// </summary>
        internal static string Mod_AllCratesWumpa {
            get {
                return ResourceManager.GetString("Mod_AllCratesWumpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All regular crates are replaced with Wumpa fruit..
        /// </summary>
        internal static string Mod_AllCratesWumpaDesc {
            get {
                return ResourceManager.GetString("Mod_AllCratesWumpaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wider Camera Field-Of-View.
        /// </summary>
        internal static string Mod_CameraWideFOV {
            get {
                return ResourceManager.GetString("Mod_CameraWideFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The camera is further away from the player than normal (recommended for Backwards Levels).
        /// </summary>
        internal static string Mod_CameraWideFOVDesc {
            get {
                return ResourceManager.GetString("Mod_CameraWideFOVDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greyscale Objects.
        /// </summary>
        internal static string Mod_GreyscaleObjects {
            get {
                return ResourceManager.GetString("Mod_GreyscaleObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object colors are greyed out..
        /// </summary>
        internal static string Mod_GreyscaleObjectsDesc {
            get {
                return ResourceManager.GetString("Mod_GreyscaleObjectsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greyscale World.
        /// </summary>
        internal static string Mod_GreyscaleWorld {
            get {
                return ResourceManager.GetString("Mod_GreyscaleWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scenery colors are greyed out..
        /// </summary>
        internal static string Mod_GreyscaleWorldDesc {
            get {
                return ResourceManager.GetString("Mod_GreyscaleWorldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Crates Are Invisible.
        /// </summary>
        internal static string Mod_InvisibleCrates {
            get {
                return ResourceManager.GetString("Mod_InvisibleCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All crates are invisible until you touch them..
        /// </summary>
        internal static string Mod_InvisibleCratesDesc {
            get {
                return ResourceManager.GetString("Mod_InvisibleCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Enemies.
        /// </summary>
        internal static string Mod_RemoveEnemies {
            get {
                return ResourceManager.GetString("Mod_RemoveEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All enemies and hazaards are removed..
        /// </summary>
        internal static string Mod_RemoveEnemiesDesc {
            get {
                return ResourceManager.GetString("Mod_RemoveEnemiesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untextured World.
        /// </summary>
        internal static string Mod_UntexturedWorld {
            get {
                return ResourceManager.GetString("Mod_UntexturedWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scenery&apos;s textures are disabled (only colors remain)..
        /// </summary>
        internal static string Mod_UntexturedWorldDesc {
            get {
                return ResourceManager.GetString("Mod_UntexturedWorldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pants Color.
        /// </summary>
        internal static string Prop_PantsColor {
            get {
                return ResourceManager.GetString("Prop_PantsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the color of Crash&apos;s pants..
        /// </summary>
        internal static string Prop_PantsColorDesc {
            get {
                return ResourceManager.GetString("Prop_PantsColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Levels Are Backwards.
        /// </summary>
        internal static string Rand_BackwardsLevels {
            get {
                return ResourceManager.GetString("Rand_BackwardsLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any supported level has a random chance of being backwards..
        /// </summary>
        internal static string Rand_BackwardsLevelsDesc {
            get {
                return ResourceManager.GetString("Rand_BackwardsLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Camera Field-Of-View.
        /// </summary>
        internal static string Rand_CameraFOV {
            get {
                return ResourceManager.GetString("Rand_CameraFOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance between the camera and the player is randomized..
        /// </summary>
        internal static string Rand_CameraFOVDesc {
            get {
                return ResourceManager.GetString("Rand_CameraFOVDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Crate Contents.
        /// </summary>
        internal static string Rand_CrateContents {
            get {
                return ResourceManager.GetString("Rand_CrateContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents of regular crates are randomized between different amounts of Wumpa, an extra life, and a mask..
        /// </summary>
        internal static string Rand_CrateContentsDesc {
            get {
                return ResourceManager.GetString("Rand_CrateContentsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Crate Counter.
        /// </summary>
        internal static string Rand_CrateCounter {
            get {
                return ResourceManager.GetString("Rand_CrateCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize the number of required crates to break to get a gem in each level. Breaking more crates than required will not grant a gem. Overridden by Random/All Enemies Are Random Crates and Random Crates Removed..
        /// </summary>
        internal static string Rand_CrateCounterDesc {
            get {
                return ResourceManager.GetString("Rand_CrateCounterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Crate Parameters.
        /// </summary>
        internal static string Rand_CrateParams {
            get {
                return ResourceManager.GetString("Rand_CrateParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random crates can float like in water or space..
        /// </summary>
        internal static string Rand_CrateParamsDesc {
            get {
                return ResourceManager.GetString("Rand_CrateParamsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Wooden Crates.
        /// </summary>
        internal static string Rand_Crates {
            get {
                return ResourceManager.GetString("Rand_Crates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizes wooden crate types from available ones in each level..
        /// </summary>
        internal static string Rand_CratesDesc {
            get {
                return ResourceManager.GetString("Rand_CratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Crates Removed.
        /// </summary>
        internal static string Rand_CratesRemoved {
            get {
                return ResourceManager.GetString("Rand_CratesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A random amount of crates is removed in each level. The box counter is adjusted accordingly..
        /// </summary>
        internal static string Rand_CratesRemovedDesc {
            get {
                return ResourceManager.GetString("Rand_CratesRemovedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Enemies Removed.
        /// </summary>
        internal static string Rand_EnemiesRemoved {
            get {
                return ResourceManager.GetString("Rand_EnemiesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random enemies and hazards are removed in each level..
        /// </summary>
        internal static string Rand_EnemiesRemovedDesc {
            get {
                return ResourceManager.GetString("Rand_EnemiesRemovedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Enemies Are Random Crates (Beta).
        /// </summary>
        internal static string Rand_EnemyCrates {
            get {
                return ResourceManager.GetString("Rand_EnemyCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random enemies and hazards are turned into random crates in each level. The box counter is adjusted accordingly..
        /// </summary>
        internal static string Rand_EnemyCratesDesc {
            get {
                return ResourceManager.GetString("Rand_EnemyCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Enemy Paths.
        /// </summary>
        internal static string Rand_EnemyPaths {
            get {
                return ResourceManager.GetString("Rand_EnemyPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths of enemies are randomized..
        /// </summary>
        internal static string Rand_EnemyPathsDesc {
            get {
                return ResourceManager.GetString("Rand_EnemyPathsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Crates Are Invisible.
        /// </summary>
        internal static string Rand_InvisibleCrates {
            get {
                return ResourceManager.GetString("Rand_InvisibleCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random crates are invisible until you touch them..
        /// </summary>
        internal static string Rand_InvisibleCratesDesc {
            get {
                return ResourceManager.GetString("Rand_InvisibleCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Object Colors.
        /// </summary>
        internal static string Rand_ObjCol {
            get {
                return ResourceManager.GetString("Rand_ObjCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors used in objects are shuffled around..
        /// </summary>
        internal static string Rand_ObjColDesc {
            get {
                return ResourceManager.GetString("Rand_ObjColDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swizzle Object Palette.
        /// </summary>
        internal static string Rand_ObjectPalette {
            get {
                return ResourceManager.GetString("Rand_ObjectPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swizzle the object colors into a random shade..
        /// </summary>
        internal static string Rand_ObjectPaletteDesc {
            get {
                return ResourceManager.GetString("Rand_ObjectPaletteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Object Textures.
        /// </summary>
        internal static string Rand_ObjTex {
            get {
                return ResourceManager.GetString("Rand_ObjTex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures and animated textures used in objects are shuffled around..
        /// </summary>
        internal static string Rand_ObjTexDesc {
            get {
                return ResourceManager.GetString("Rand_ObjTexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Pants Color.
        /// </summary>
        internal static string Rand_PantsColor {
            get {
                return ResourceManager.GetString("Rand_PantsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize the color of Crash&apos;s pants..
        /// </summary>
        internal static string Rand_PantsColorDesc {
            get {
                return ResourceManager.GetString("Rand_PantsColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Sound Effects.
        /// </summary>
        internal static string Rand_SFX {
            get {
                return ResourceManager.GetString("Rand_SFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sound effects in each level are randomized between each other..
        /// </summary>
        internal static string Rand_SFXDesc {
            get {
                return ResourceManager.GetString("Rand_SFXDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Streamed Audio (Cutscenes, etc.).
        /// </summary>
        internal static string Rand_Streams {
            get {
                return ResourceManager.GetString("Rand_Streams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The streamed audio used for cutscenes and Aku Aku hints is randomly shuffled around in each level..
        /// </summary>
        internal static string Rand_StreamsDesc {
            get {
                return ResourceManager.GetString("Rand_StreamsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Wooden Crates.
        /// </summary>
        internal static string Rand_WoodenCrates {
            get {
                return ResourceManager.GetString("Rand_WoodenCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The types of some wooden crates are randomized..
        /// </summary>
        internal static string Rand_WoodenCratesDesc {
            get {
                return ResourceManager.GetString("Rand_WoodenCratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize World Colors.
        /// </summary>
        internal static string Rand_WorldColors {
            get {
                return ResourceManager.GetString("Rand_WorldColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize World Colors.
        /// </summary>
        internal static string Rand_WorldColors1 {
            get {
                return ResourceManager.GetString("Rand_WorldColors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scenery colors are randomized in each level..
        /// </summary>
        internal static string Rand_WorldColorsDesc {
            get {
                return ResourceManager.GetString("Rand_WorldColorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scenery colors are randomized in each level..
        /// </summary>
        internal static string Rand_WorldColorsDesc1 {
            get {
                return ResourceManager.GetString("Rand_WorldColorsDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize World Palette.
        /// </summary>
        internal static string Rand_WorldPalette {
            get {
                return ResourceManager.GetString("Rand_WorldPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swizzle World Palette.
        /// </summary>
        internal static string Rand_WorldPalette1 {
            get {
                return ResourceManager.GetString("Rand_WorldPalette1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scenery color palette is randomized in each level..
        /// </summary>
        internal static string Rand_WorldPaletteDesc {
            get {
                return ResourceManager.GetString("Rand_WorldPaletteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swizzle the scenery colors into a random shade..
        /// </summary>
        internal static string Rand_WorldPaletteDesc1 {
            get {
                return ResourceManager.GetString("Rand_WorldPaletteDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize World Textures.
        /// </summary>
        internal static string Rand_WorldTex {
            get {
                return ResourceManager.GetString("Rand_WorldTex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures and animated textures used in scenery are shuffled around..
        /// </summary>
        internal static string Rand_WorldTexDesc {
            get {
                return ResourceManager.GetString("Rand_WorldTexDesc", resourceCulture);
            }
        }
    }
}
