//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModLoader.GameSpecific.CrashTS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Twins_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Twins_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModLoader.GameSpecific.CrashTS.Twins_Text", typeof(Twins_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API by NeoKesha, Smartkin, ManDude, BetaM and Marko.
        /// </summary>
        internal static string API_Credit {
            get {
                return ResourceManager.GetString("API_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Gravity.
        /// </summary>
        internal static string CharFloats_AirGravity {
            get {
                return ResourceManager.GetString("CharFloats_AirGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object gravity while not grounded.
        /// </summary>
        internal static string CharFloats_AirGravityDesc {
            get {
                return ResourceManager.GetString("CharFloats_AirGravityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Gravity.
        /// </summary>
        internal static string CharFloats_BaseGravity {
            get {
                return ResourceManager.GetString("CharFloats_BaseGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object gravity on the ground.
        /// </summary>
        internal static string CharFloats_BaseGravityDesc {
            get {
                return ResourceManager.GetString("CharFloats_BaseGravityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyslam Gravity Force.
        /// </summary>
        internal static string CharFloats_BodyslamGravityForce {
            get {
                return ResourceManager.GetString("CharFloats_BodyslamGravityForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much the bodyslam slams downward after it&apos;s done flying upward.
        /// </summary>
        internal static string CharFloats_BodyslamGravityForceDesc {
            get {
                return ResourceManager.GetString("CharFloats_BodyslamGravityForceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyslam Hang Time.
        /// </summary>
        internal static string CharFloats_BodyslamHangTime {
            get {
                return ResourceManager.GetString("CharFloats_BodyslamHangTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to 0 to disable bodyslam.
        /// </summary>
        internal static string CharFloats_BodyslamHangTimeDesc {
            get {
                return ResourceManager.GetString("CharFloats_BodyslamHangTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodyslam Upward Force.
        /// </summary>
        internal static string CharFloats_BodyslamUpwardForce {
            get {
                return ResourceManager.GetString("CharFloats_BodyslamUpwardForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much the bodyslam flies upward after it starts.
        /// </summary>
        internal static string CharFloats_BodyslamUpwardForceDesc {
            get {
                return ResourceManager.GetString("CharFloats_BodyslamUpwardForceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl Speed.
        /// </summary>
        internal static string CharFloats_CrawlSpeed {
            get {
                return ResourceManager.GetString("CharFloats_CrawlSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed of crawling.
        /// </summary>
        internal static string CharFloats_CrawlSpeedDesc {
            get {
                return ResourceManager.GetString("CharFloats_CrawlSpeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl Time From Stand.
        /// </summary>
        internal static string CharFloats_CrawlTimeFromStand {
            get {
                return ResourceManager.GetString("CharFloats_CrawlTimeFromStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from standing to crouched, Set to 0 to disable crawl from standing.
        /// </summary>
        internal static string CharFloats_CrawlTimeFromStandDesc {
            get {
                return ResourceManager.GetString("CharFloats_CrawlTimeFromStandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl Time To Run.
        /// </summary>
        internal static string CharFloats_CrawlTimeToRun {
            get {
                return ResourceManager.GetString("CharFloats_CrawlTimeToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from crawling to running.
        /// </summary>
        internal static string CharFloats_CrawlTimeToRunDesc {
            get {
                return ResourceManager.GetString("CharFloats_CrawlTimeToRunDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl Time To Stand.
        /// </summary>
        internal static string CharFloats_CrawlTimeToStand {
            get {
                return ResourceManager.GetString("CharFloats_CrawlTimeToStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from crouched to standing.
        /// </summary>
        internal static string CharFloats_CrawlTimeToStandDesc {
            get {
                return ResourceManager.GetString("CharFloats_CrawlTimeToStandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Jump Arc Unknown Value.
        /// </summary>
        internal static string CharFloats_DoubleJumpArcUnk {
            get {
                return ResourceManager.GetString("CharFloats_DoubleJumpArcUnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory for double jump to work.
        /// </summary>
        internal static string CharFloats_DoubleJumpArcUnkDesc {
            get {
                return ResourceManager.GetString("CharFloats_DoubleJumpArcUnkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Jump Height.
        /// </summary>
        internal static string CharFloats_DoubleJumpHeight {
            get {
                return ResourceManager.GetString("CharFloats_DoubleJumpHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to 0 to disable double jump, non-zero to enable double jump.
        /// </summary>
        internal static string CharFloats_DoubleJumpHeightDesc {
            get {
                return ResourceManager.GetString("CharFloats_DoubleJumpHeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Jump Unknown Value 22.
        /// </summary>
        internal static string CharFloats_DoubleJumpUnk22 {
            get {
                return ResourceManager.GetString("CharFloats_DoubleJumpUnk22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory for double jump to work.
        /// </summary>
        internal static string CharFloats_DoubleJumpUnk22Desc {
            get {
                return ResourceManager.GetString("CharFloats_DoubleJumpUnk22Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying Kick Forward Speed.
        /// </summary>
        internal static string CharFloats_FlyingKickForwardSpeed {
            get {
                return ResourceManager.GetString("CharFloats_FlyingKickForwardSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How fast the flying kick is.
        /// </summary>
        internal static string CharFloats_FlyingKickForwardSpeedDesc {
            get {
                return ResourceManager.GetString("CharFloats_FlyingKickForwardSpeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying Kick Gravity.
        /// </summary>
        internal static string CharFloats_FlyingKickGravity {
            get {
                return ResourceManager.GetString("CharFloats_FlyingKickGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall gravity after the flying kick ends (only applies when walking off edges for some reason).
        /// </summary>
        internal static string CharFloats_FlyingKickGravityDesc {
            get {
                return ResourceManager.GetString("CharFloats_FlyingKickGravityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying Kick Hang Time.
        /// </summary>
        internal static string CharFloats_FlyingKickHangTime {
            get {
                return ResourceManager.GetString("CharFloats_FlyingKickHangTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long the Flying Kick lasts, Set to 0 to disable flying kick, unused move, replaces bodyslam of the single jump (not double jump).
        /// </summary>
        internal static string CharFloats_FlyingKickHangTimeDesc {
            get {
                return ResourceManager.GetString("CharFloats_FlyingKickHangTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Button Hold Time To Start Charging.
        /// </summary>
        internal static string CharFloats_GunButtonHoldTimeToStartCharging {
            get {
                return ResourceManager.GetString("CharFloats_GunButtonHoldTimeToStartCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long should the firing button be held to start charging.
        /// </summary>
        internal static string CharFloats_GunButtonHoldTimeToStartChargingDesc {
            get {
                return ResourceManager.GetString("CharFloats_GunButtonHoldTimeToStartChargingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Charge Time.
        /// </summary>
        internal static string CharFloats_GunChargeTime {
            get {
                return ResourceManager.GetString("CharFloats_GunChargeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long the gun charges the shot.
        /// </summary>
        internal static string CharFloats_GunChargeTimeDesc {
            get {
                return ResourceManager.GetString("CharFloats_GunChargeTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Time Between Charged Shots.
        /// </summary>
        internal static string CharFloats_GunTimeBetweenChargedShots {
            get {
                return ResourceManager.GetString("CharFloats_GunTimeBetweenChargedShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long until the next charged shot fires while still holding the firing button.
        /// </summary>
        internal static string CharFloats_GunTimeBetweenChargedShotsDesc {
            get {
                return ResourceManager.GetString("CharFloats_GunTimeBetweenChargedShotsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Time Between Shots.
        /// </summary>
        internal static string CharFloats_GunTimeBetweenShots {
            get {
                return ResourceManager.GetString("CharFloats_GunTimeBetweenShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How fast can regular shots be fired.
        /// </summary>
        internal static string CharFloats_GunTimeBetweenShotsDesc {
            get {
                return ResourceManager.GetString("CharFloats_GunTimeBetweenShotsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Air Speed.
        /// </summary>
        internal static string CharFloats_JumpAirSpeed {
            get {
                return ResourceManager.GetString("CharFloats_JumpAirSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed while in mid-air.
        /// </summary>
        internal static string CharFloats_JumpAirSpeedDesc {
            get {
                return ResourceManager.GetString("CharFloats_JumpAirSpeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Arc Unknown Value 18.
        /// </summary>
        internal static string CharFloats_JumpArcUnk18 {
            get {
                return ResourceManager.GetString("CharFloats_JumpArcUnk18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump arc variable.
        /// </summary>
        internal static string CharFloats_JumpArcUnk18Desc {
            get {
                return ResourceManager.GetString("CharFloats_JumpArcUnk18Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Arc Unknown Value 19.
        /// </summary>
        internal static string CharFloats_JumpArcUnk19 {
            get {
                return ResourceManager.GetString("CharFloats_JumpArcUnk19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump arc variable.
        /// </summary>
        internal static string CharFloats_JumpArcUnk19Desc {
            get {
                return ResourceManager.GetString("CharFloats_JumpArcUnk19Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Edge Speed.
        /// </summary>
        internal static string CharFloats_JumpEdgeSpeed {
            get {
                return ResourceManager.GetString("CharFloats_JumpEdgeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump speed off of edge (when long jump and flying kick aren&apos;t stored).
        /// </summary>
        internal static string CharFloats_JumpEdgeSpeedDesc {
            get {
                return ResourceManager.GetString("CharFloats_JumpEdgeSpeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump Height.
        /// </summary>
        internal static string CharFloats_JumpHeight {
            get {
                return ResourceManager.GetString("CharFloats_JumpHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single jump height.
        /// </summary>
        internal static string CharFloats_JumpHeightDesc {
            get {
                return ResourceManager.GetString("CharFloats_JumpHeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Blast Charge Time.
        /// </summary>
        internal static string CharFloats_RadialBlastChargeTime {
            get {
                return ResourceManager.GetString("CharFloats_RadialBlastChargeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long the radial blast charges while in mid-air.
        /// </summary>
        internal static string CharFloats_RadialBlastChargeTimeDesc {
            get {
                return ResourceManager.GetString("CharFloats_RadialBlastChargeTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Blast Time To Start.
        /// </summary>
        internal static string CharFloats_RadialBlastTimeToStart {
            get {
                return ResourceManager.GetString("CharFloats_RadialBlastTimeToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to 0 to disable radial blast, radial blast replaces single jump bodyslam.
        /// </summary>
        internal static string CharFloats_RadialBlastTimeToStartDesc {
            get {
                return ResourceManager.GetString("CharFloats_RadialBlastTimeToStartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Blast Unknown Value 39.
        /// </summary>
        internal static string CharFloats_RadialBlastUnk39 {
            get {
                return ResourceManager.GetString("CharFloats_RadialBlastUnk39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial blast velocity value.
        /// </summary>
        internal static string CharFloats_RadialBlastUnk39Desc {
            get {
                return ResourceManager.GetString("CharFloats_RadialBlastUnk39Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Blast Unknown Value 40.
        /// </summary>
        internal static string CharFloats_RadialBlastUnk40 {
            get {
                return ResourceManager.GetString("CharFloats_RadialBlastUnk40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial blast velocity value.
        /// </summary>
        internal static string CharFloats_RadialBlastUnk40Desc {
            get {
                return ResourceManager.GetString("CharFloats_RadialBlastUnk40Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Speed.
        /// </summary>
        internal static string CharFloats_RunSpeed {
            get {
                return ResourceManager.GetString("CharFloats_RunSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runninng speed on the ground.
        /// </summary>
        internal static string CharFloats_RunSpeedDesc {
            get {
                return ResourceManager.GetString("CharFloats_RunSpeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Jump Unknown Value 24.
        /// </summary>
        internal static string CharFloats_SlideJumpUnk24 {
            get {
                return ResourceManager.GetString("CharFloats_SlideJumpUnk24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide jump speed.
        /// </summary>
        internal static string CharFloats_SlideJumpUnk24Desc {
            get {
                return ResourceManager.GetString("CharFloats_SlideJumpUnk24Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Jump Unknown Value 25.
        /// </summary>
        internal static string CharFloats_SlideJumpUnk25 {
            get {
                return ResourceManager.GetString("CharFloats_SlideJumpUnk25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide jump variable.
        /// </summary>
        internal static string CharFloats_SlideJumpUnk25Desc {
            get {
                return ResourceManager.GetString("CharFloats_SlideJumpUnk25Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Jump Unknown Value 26.
        /// </summary>
        internal static string CharFloats_SlideJumpUnk26 {
            get {
                return ResourceManager.GetString("CharFloats_SlideJumpUnk26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide jump variable.
        /// </summary>
        internal static string CharFloats_SlideJumpUnk26Desc {
            get {
                return ResourceManager.GetString("CharFloats_SlideJumpUnk26Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Jump Unknown Value 27.
        /// </summary>
        internal static string CharFloats_SlideJumpUnk27 {
            get {
                return ResourceManager.GetString("CharFloats_SlideJumpUnk27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide jump arc variable.
        /// </summary>
        internal static string CharFloats_SlideJumpUnk27Desc {
            get {
                return ResourceManager.GetString("CharFloats_SlideJumpUnk27Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Slowdown Time.
        /// </summary>
        internal static string CharFloats_SlideSlowdownTime {
            get {
                return ResourceManager.GetString("CharFloats_SlideSlowdownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Slowdown Time 2.
        /// </summary>
        internal static string CharFloats_SlideSlowdownTime2 {
            get {
                return ResourceManager.GetString("CharFloats_SlideSlowdownTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide variable.
        /// </summary>
        internal static string CharFloats_SlideSlowdownTime2Desc {
            get {
                return ResourceManager.GetString("CharFloats_SlideSlowdownTime2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Slowdown Time 3.
        /// </summary>
        internal static string CharFloats_SlideSlowdownTime3 {
            get {
                return ResourceManager.GetString("CharFloats_SlideSlowdownTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide variable.
        /// </summary>
        internal static string CharFloats_SlideSlowdownTime3Desc {
            get {
                return ResourceManager.GetString("CharFloats_SlideSlowdownTime3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide variable.
        /// </summary>
        internal static string CharFloats_SlideSlowdownTimeDesc {
            get {
                return ResourceManager.GetString("CharFloats_SlideSlowdownTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Speed.
        /// </summary>
        internal static string CharFloats_SlideSpeed {
            get {
                return ResourceManager.GetString("CharFloats_SlideSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to 0 to disable slide.
        /// </summary>
        internal static string CharFloats_SlideSpeedDesc {
            get {
                return ResourceManager.GetString("CharFloats_SlideSpeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Unknown Value 49.
        /// </summary>
        internal static string CharFloats_SlideUnk49 {
            get {
                return ResourceManager.GetString("CharFloats_SlideUnk49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide variable.
        /// </summary>
        internal static string CharFloats_SlideUnk49Desc {
            get {
                return ResourceManager.GetString("CharFloats_SlideUnk49Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Unknown Value 50.
        /// </summary>
        internal static string CharFloats_SlideUnk50 {
            get {
                return ResourceManager.GetString("CharFloats_SlideUnk50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide variable.
        /// </summary>
        internal static string CharFloats_SlideUnk50Desc {
            get {
                return ResourceManager.GetString("CharFloats_SlideUnk50Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin Delay.
        /// </summary>
        internal static string CharFloats_SpinDelay {
            get {
                return ResourceManager.GetString("CharFloats_SpinDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between spins.
        /// </summary>
        internal static string CharFloats_SpinDelayDesc {
            get {
                return ResourceManager.GetString("CharFloats_SpinDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin Length.
        /// </summary>
        internal static string CharFloats_SpinLength {
            get {
                return ResourceManager.GetString("CharFloats_SpinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of spinning time.
        /// </summary>
        internal static string CharFloats_SpinLengthDesc {
            get {
                return ResourceManager.GetString("CharFloats_SpinLengthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin Throw Forward Force.
        /// </summary>
        internal static string CharFloats_SpinThrowForwardForce {
            get {
                return ResourceManager.GetString("CharFloats_SpinThrowForwardForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward force after starting a spin throw.
        /// </summary>
        internal static string CharFloats_SpinThrowForwardForceDesc {
            get {
                return ResourceManager.GetString("CharFloats_SpinThrowForwardForceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Value 1.
        /// </summary>
        internal static string CharFloats_Static1 {
            get {
                return ResourceManager.GetString("CharFloats_Static1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Value 15.
        /// </summary>
        internal static string CharFloats_Static15 {
            get {
                return ResourceManager.GetString("CharFloats_Static15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Static15Desc {
            get {
                return ResourceManager.GetString("CharFloats_Static15Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Static1Desc {
            get {
                return ResourceManager.GetString("CharFloats_Static1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Value 6.
        /// </summary>
        internal static string CharFloats_Static6 {
            get {
                return ResourceManager.GetString("CharFloats_Static6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Static6Desc {
            get {
                return ResourceManager.GetString("CharFloats_Static6Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strafing Speed.
        /// </summary>
        internal static string CharFloats_StrafingSpeed {
            get {
                return ResourceManager.GetString("CharFloats_StrafingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to 0 to disable strafing, non-zero to enable strafing.
        /// </summary>
        internal static string CharFloats_StrafingSpeedDesc {
            get {
                return ResourceManager.GetString("CharFloats_StrafingSpeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Value 13.
        /// </summary>
        internal static string CharFloats_Unk13 {
            get {
                return ResourceManager.GetString("CharFloats_Unk13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Unk13Desc {
            get {
                return ResourceManager.GetString("CharFloats_Unk13Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Value 14.
        /// </summary>
        internal static string CharFloats_Unk14 {
            get {
                return ResourceManager.GetString("CharFloats_Unk14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Unk14Desc {
            get {
                return ResourceManager.GetString("CharFloats_Unk14Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Value 28.
        /// </summary>
        internal static string CharFloats_Unk28 {
            get {
                return ResourceManager.GetString("CharFloats_Unk28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Unk28Desc {
            get {
                return ResourceManager.GetString("CharFloats_Unk28Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Value 29.
        /// </summary>
        internal static string CharFloats_Unk29 {
            get {
                return ResourceManager.GetString("CharFloats_Unk29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Unk29Desc {
            get {
                return ResourceManager.GetString("CharFloats_Unk29Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Value 3.
        /// </summary>
        internal static string CharFloats_Unk3 {
            get {
                return ResourceManager.GetString("CharFloats_Unk3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Value 30.
        /// </summary>
        internal static string CharFloats_Unk30 {
            get {
                return ResourceManager.GetString("CharFloats_Unk30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Unk30Desc {
            get {
                return ResourceManager.GetString("CharFloats_Unk30Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Value 31.
        /// </summary>
        internal static string CharFloats_Unk31 {
            get {
                return ResourceManager.GetString("CharFloats_Unk31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Unk31Desc {
            get {
                return ResourceManager.GetString("CharFloats_Unk31Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Unk3Desc {
            get {
                return ResourceManager.GetString("CharFloats_Unk3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Value 55.
        /// </summary>
        internal static string CharFloats_Unk55 {
            get {
                return ResourceManager.GetString("CharFloats_Unk55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CharFloats_Unk55Desc {
            get {
                return ResourceManager.GetString("CharFloats_Unk55Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk Speed.
        /// </summary>
        internal static string CharFloats_WalkSpeed {
            get {
                return ResourceManager.GetString("CharFloats_WalkSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking speed on the ground.
        /// </summary>
        internal static string CharFloats_WalkSpeedDesc {
            get {
                return ResourceManager.GetString("CharFloats_WalkSpeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk Speed Percentage.
        /// </summary>
        internal static string CharFloats_WalkSpeedPercentage {
            get {
                return ResourceManager.GetString("CharFloats_WalkSpeedPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of run speed as integer? Walk-to-run speed scaling?.
        /// </summary>
        internal static string CharFloats_WalkSpeedPercentageDesc {
            get {
                return ResourceManager.GetString("CharFloats_WalkSpeedPercentageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn Health.
        /// </summary>
        internal static string CharInts_SpawnHealth {
            get {
                return ResourceManager.GetString("CharInts_SpawnHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much health characters spawn with (1 - no mask, 2 - one mask, 3 - two masks).
        /// </summary>
        internal static string CharInts_SpawnHealthDesc {
            get {
                return ResourceManager.GetString("CharInts_SpawnHealthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Twinsanity.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Crate Persistence.
        /// </summary>
        internal static string Mod_ClassicCratePersistence {
            get {
                return ResourceManager.GetString("Mod_ClassicCratePersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken crates don&apos;t respawn after a death..
        /// </summary>
        internal static string Mod_ClassicCratePersistenceDesc {
            get {
                return ResourceManager.GetString("Mod_ClassicCratePersistenceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Explosion Damage.
        /// </summary>
        internal static string Mod_ClassicExplosionDaamge {
            get {
                return ResourceManager.GetString("Mod_ClassicExplosionDaamge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosions only take away a mask..
        /// </summary>
        internal static string Mod_ClassicExplosionDamageDesc {
            get {
                return ResourceManager.GetString("Mod_ClassicExplosionDamageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Health.
        /// </summary>
        internal static string Mod_ClassicHealth {
            get {
                return ResourceManager.GetString("Mod_ClassicHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn without a mask..
        /// </summary>
        internal static string Mod_ClassicHealthDesc {
            get {
                return ResourceManager.GetString("Mod_ClassicHealthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Double Jump for Cortex.
        /// </summary>
        internal static string Mod_CortexDoubleJump {
            get {
                return ResourceManager.GetString("Mod_CortexDoubleJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let Cortex jump twice by pressing the jump button twice..
        /// </summary>
        internal static string Mod_CortexDoubleJumpDesc {
            get {
                return ResourceManager.GetString("Mod_CortexDoubleJumpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Flying Kick for Crash.
        /// </summary>
        internal static string Mod_FlyingKick {
            get {
                return ResourceManager.GetString("Mod_FlyingKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the jump button and then the slide button to strike the unused Flying Kick move..
        /// </summary>
        internal static string Mod_FlyingKickDesc {
            get {
                return ResourceManager.GetString("Mod_FlyingKickDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Double Jump for Nina.
        /// </summary>
        internal static string Mod_NinaDoubleJump {
            get {
                return ResourceManager.GetString("Mod_NinaDoubleJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let Nina jump twice by pressing the jump button twice..
        /// </summary>
        internal static string Mod_NinaDoubleJumpDesc {
            get {
                return ResourceManager.GetString("Mod_NinaDoubleJumpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Stomp Kick for Crash.
        /// </summary>
        internal static string Mod_StompKick {
            get {
                return ResourceManager.GetString("Mod_StompKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the jump button and then the slide button to strike the unused Stomp Kick move. It replaces the Flying Kick move..
        /// </summary>
        internal static string Mod_StompKickDesc {
            get {
                return ResourceManager.GetString("Mod_StompKickDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Characters At Will.
        /// </summary>
        internal static string Mod_SwitchCharacters {
            get {
                return ResourceManager.GetString("Mod_SwitchCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between Crash and Cortex when near them using L1/R1 buttons. Use with caution - it&apos;s easy to softlock!.
        /// </summary>
        internal static string Mod_SwitchCharactersDesc {
            get {
                return ResourceManager.GetString("Mod_SwitchCharactersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Unused Enemies.
        /// </summary>
        internal static string Mod_UnusedEnemies {
            get {
                return ResourceManager.GetString("Mod_UnusedEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables unused enemies in Jungle Bungle and Classroom Chaos..
        /// </summary>
        internal static string Mod_UnusedEnemiesDesc {
            get {
                return ResourceManager.GetString("Mod_UnusedEnemiesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Character Parameters.
        /// </summary>
        internal static string Rand_CharParams {
            get {
                return ResourceManager.GetString("Rand_CharParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizes each characters parameters like speed and jump height..
        /// </summary>
        internal static string Rand_CharParamsDesc {
            get {
                return ResourceManager.GetString("Rand_CharParamsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Individual Crates.
        /// </summary>
        internal static string Rand_Crates {
            get {
                return ResourceManager.GetString("Rand_Crates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each individual regular crate&apos;s type is randomized..
        /// </summary>
        internal static string Rand_CratesDesc {
            get {
                return ResourceManager.GetString("Rand_CratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Crate Types.
        /// </summary>
        internal static string Rand_CrateTypes {
            get {
                return ResourceManager.GetString("Rand_CrateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate types are shuffled around. (not each individual crate).
        /// </summary>
        internal static string Rand_CrateTypesDesc {
            get {
                return ResourceManager.GetString("Rand_CrateTypesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Gem Locations.
        /// </summary>
        internal static string Rand_GemLocations {
            get {
                return ResourceManager.GetString("Rand_GemLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide gems in new fair random locations across the game.  The game is 100% completable and each level has 6 gems as normal, just in different places..
        /// </summary>
        internal static string Rand_GemLocationsDesc {
            get {
                return ResourceManager.GetString("Rand_GemLocationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Level Music.
        /// </summary>
        internal static string Rand_Music {
            get {
                return ResourceManager.GetString("Rand_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize the music tracks of each level..
        /// </summary>
        internal static string Rand_MusicDesc {
            get {
                return ResourceManager.GetString("Rand_MusicDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Chunk.
        /// </summary>
        internal static string StartingChunk {
            get {
                return ResourceManager.GetString("StartingChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chunk name that the game starts in (must have a player object or else it will not load).
        /// </summary>
        internal static string StartingChunkDesc {
            get {
                return ResourceManager.GetString("StartingChunkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Chunk (Unsafe).
        /// </summary>
        internal static string UnsafeStartingChunk {
            get {
                return ResourceManager.GetString("UnsafeStartingChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows for a longer starting chunk name at the expense of the game crashing after the credits (due to overwriting the post-credits chunk).
        /// </summary>
        internal static string UnsafeStartingChunkDesc {
            get {
                return ResourceManager.GetString("UnsafeStartingChunkDesc", resourceCulture);
            }
        }
    }
}
