//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModLoader.GameSpecific.CrashTS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Twins_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Twins_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModLoader.GameSpecific.CrashTS.Twins_Text", typeof(Twins_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API by NeoKesha, Smartkin, ManDude and Marko.
        /// </summary>
        internal static string API_Credit {
            get {
                return ResourceManager.GetString("API_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Twinsanity.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Double Jump for Cortex.
        /// </summary>
        internal static string Mod_CortexDoubleJump {
            get {
                return ResourceManager.GetString("Mod_CortexDoubleJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let Cortex jump twice by pressing the jump button twice..
        /// </summary>
        internal static string Mod_CortexDoubleJumpDesc {
            get {
                return ResourceManager.GetString("Mod_CortexDoubleJumpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Flying Kick for Crash.
        /// </summary>
        internal static string Mod_FlyingKick {
            get {
                return ResourceManager.GetString("Mod_FlyingKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the jump button and then the slide button to strike the unused Flying Kick move..
        /// </summary>
        internal static string Mod_FlyingKickDesc {
            get {
                return ResourceManager.GetString("Mod_FlyingKickDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Double Jump for Nina.
        /// </summary>
        internal static string Mod_NinaDoubleJump {
            get {
                return ResourceManager.GetString("Mod_NinaDoubleJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let Nina jump twice by pressing the jump button twice..
        /// </summary>
        internal static string Mod_NinaDoubleJumpDesc {
            get {
                return ResourceManager.GetString("Mod_NinaDoubleJumpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Stomp Kick for Crash.
        /// </summary>
        internal static string Mod_StompKick {
            get {
                return ResourceManager.GetString("Mod_StompKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the jump button and then the slide button to strike the unused Stomp Kick move. It replaces the Flying Kick move..
        /// </summary>
        internal static string Mod_StompKickDesc {
            get {
                return ResourceManager.GetString("Mod_StompKickDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Unused Enemies.
        /// </summary>
        internal static string Mod_UnusedEnemies {
            get {
                return ResourceManager.GetString("Mod_UnusedEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables unused enemies in Jungle Bungle and Classroom Chaos..
        /// </summary>
        internal static string Mod_UnusedEnemiesDesc {
            get {
                return ResourceManager.GetString("Mod_UnusedEnemiesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Character Parameters.
        /// </summary>
        internal static string Rand_CharParams {
            get {
                return ResourceManager.GetString("Rand_CharParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizes each characters parameters like speed and jump height..
        /// </summary>
        internal static string Rand_CharParamsDesc {
            get {
                return ResourceManager.GetString("Rand_CharParamsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Individual Crates.
        /// </summary>
        internal static string Rand_Crates {
            get {
                return ResourceManager.GetString("Rand_Crates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each individual regular crate&apos;s type is randomized..
        /// </summary>
        internal static string Rand_CratesDesc {
            get {
                return ResourceManager.GetString("Rand_CratesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Crate Types.
        /// </summary>
        internal static string Rand_CrateTypes {
            get {
                return ResourceManager.GetString("Rand_CrateTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate types are shuffled around. (not each individual crate).
        /// </summary>
        internal static string Rand_CrateTypesDesc {
            get {
                return ResourceManager.GetString("Rand_CrateTypesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Gem Locations.
        /// </summary>
        internal static string Rand_GemLocations {
            get {
                return ResourceManager.GetString("Rand_GemLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide gems in new fair random locations across the game.  The game is 100% completable and each level has 6 gems as normal, just in different places..
        /// </summary>
        internal static string Rand_GemLocationsDesc {
            get {
                return ResourceManager.GetString("Rand_GemLocationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Level Music.
        /// </summary>
        internal static string Rand_Music {
            get {
                return ResourceManager.GetString("Rand_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize the music tracks of each level..
        /// </summary>
        internal static string Rand_MusicDesc {
            get {
                return ResourceManager.GetString("Rand_MusicDesc", resourceCulture);
            }
        }
    }
}
