//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModLoader.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModLoaderText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModLoaderText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModLoader.Resources.Text.ModLoaderText", typeof(ModLoaderText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Mods.
        /// </summary>
        public static string Button_DownloadMods {
            get {
                return ResourceManager.GetString("Button_DownloadMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Tools.
        /// </summary>
        public static string Button_ModTools {
            get {
                return ResourceManager.GetString("Button_ModTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModdedGame.
        /// </summary>
        public static string DefaultOutputFileName {
            get {
                return ResourceManager.GetString("DefaultOutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building 360 ROMs is not supported yet! Save to folder instead..
        /// </summary>
        public static string Error_360_ROMNotSupported {
            get {
                return ResourceManager.GetString("Error_360_ROMNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction error: Input directory cannot be accessed!.
        /// </summary>
        public static string Error_FolderNotAccessible {
            get {
                return ResourceManager.GetString("Error_FolderNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building ROMs from folders with this console is not supported yet!.
        /// </summary>
        public static string Error_FolderToROMNotSupported {
            get {
                return ResourceManager.GetString("Error_FolderToROMNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building GC directories is not supported yet!.
        /// </summary>
        public static string Error_GC_FolderNotSupported {
            get {
                return ResourceManager.GetString("Error_GC_FolderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC games are only supported in Folder mode!.
        /// </summary>
        public static string Error_PC_FolderOnly {
            get {
                return ResourceManager.GetString("Error_PC_FolderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the game directory!.
        /// </summary>
        public static string Error_UnableToOpenGameFolder {
            get {
                return ResourceManager.GetString("Error_UnableToOpenGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the game ROM!.
        /// </summary>
        public static string Error_UnableToOpenROM {
            get {
                return ResourceManager.GetString("Error_UnableToOpenROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown PS/GCN/WII/XBOX game ROM!.
        /// </summary>
        public static string Error_UnknownAutoGameROM {
            get {
                return ResourceManager.GetString("Error_UnknownAutoGameROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown game ROM!.
        /// </summary>
        public static string Error_UnknownGameROM {
            get {
                return ResourceManager.GetString("Error_UnknownGameROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorPopupTitle {
            get {
                return ResourceManager.GetString("ErrorPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API available.
        /// </summary>
        public static string GameHasNoAPI {
            get {
                return ResourceManager.GetString("GameHasNoAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) Browse....
        /// </summary>
        public static string InputBrowse {
            get {
                return ResourceManager.GetString("InputBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported ROM formats.
        /// </summary>
        public static string InputDialogTypeAuto {
            get {
                return ResourceManager.GetString("InputDialogTypeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Folder.
        /// </summary>
        public static string InputFolder {
            get {
                return ResourceManager.GetString("InputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Click &quot;Browse&quot; to select the game or drag &amp; drop it here..
        /// </summary>
        public static string InputInstruction {
            get {
                return ResourceManager.GetString("InputInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Temp Files.
        /// </summary>
        public static string KeepTempFiles {
            get {
                return ResourceManager.GetString("KeepTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open link..
        /// </summary>
        public static string LinkOpenFail {
            get {
                return ResourceManager.GetString("LinkOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify Mod Crate at:.
        /// </summary>
        public static string ModCrateErrorPopup {
            get {
                return ResourceManager.GetString("ModCrateErrorPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string ModCrateManagerAuthorText {
            get {
                return ResourceManager.GetString("ModCrateManagerAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ModCrateManagerConfirmButton {
            get {
                return ResourceManager.GetString("ModCrateManagerConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Mod Crate.
        /// </summary>
        public static string ModCrateManagerImportModButton {
            get {
                return ResourceManager.GetString("ModCrateManagerImportModButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Crate Manager.
        /// </summary>
        public static string ModCrateManagerTitle {
            get {
                return ResourceManager.GetString("ModCrateManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Crates.
        /// </summary>
        public static string ModCratesButton {
            get {
                return ResourceManager.GetString("ModCratesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Menu.
        /// </summary>
        public static string ModMenuButton {
            get {
                return ResourceManager.GetString("ModMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No settings found!.
        /// </summary>
        public static string ModMenuLoad_Error {
            get {
                return ResourceManager.GetString("ModMenuLoad_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game doesn&apos;t have a mod menu!.
        /// </summary>
        public static string ModMenuMissingErrorPopup {
            get {
                return ResourceManager.GetString("ModMenuMissingErrorPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string ModMenuPage {
            get {
                return ResourceManager.GetString("ModMenuPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options specified - Output ROM will only display version info ingame if available. Proceed?.
        /// </summary>
        public static string NoOptionsSelectedPopup {
            get {
                return ResourceManager.GetString("NoOptionsSelectedPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Options Selected.
        /// </summary>
        public static string NoOptionsSelectedTitle {
            get {
                return ResourceManager.GetString("NoOptionsSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (2) Browse....
        /// </summary>
        public static string OutputBrowse {
            get {
                return ResourceManager.GetString("OutputBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string OutputDialogTypeAllFiles {
            get {
                return ResourceManager.GetString("OutputDialogTypeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Folder.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Click &quot;Browse&quot; to choose the output path..
        /// </summary>
        public static string OutputInstruction {
            get {
                return ResourceManager.GetString("OutputInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled!.
        /// </summary>
        public static string Process_Cancelled {
            get {
                return ResourceManager.GetString("Process_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string Process_Error {
            get {
                return ResourceManager.GetString("Process_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        public static string Process_Finished {
            get {
                return ResourceManager.GetString("Process_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing....
        /// </summary>
        public static string Process_Step0 {
            get {
                return ResourceManager.GetString("Process_Step0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files....
        /// </summary>
        public static string Process_Step1_Folder {
            get {
                return ResourceManager.GetString("Process_Step1_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting game....
        /// </summary>
        public static string Process_Step1_ROM {
            get {
                return ResourceManager.GetString("Process_Step1_ROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modding game....
        /// </summary>
        public static string Process_Step2 {
            get {
                return ResourceManager.GetString("Process_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying modded files....
        /// </summary>
        public static string Process_Step3_Folder {
            get {
                return ResourceManager.GetString("Process_Step3_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building game....
        /// </summary>
        public static string Process_Step3_ROM {
            get {
                return ResourceManager.GetString("Process_Step3_ROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready!.
        /// </summary>
        public static string ProcessReady {
            get {
                return ResourceManager.GetString("ProcessReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate Mod Loader.
        /// </summary>
        public static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Seed.
        /// </summary>
        public static string RandomizeSeedButton {
            get {
                return ResourceManager.GetString("RandomizeSeedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start!.
        /// </summary>
        public static string StartProcessButton {
            get {
                return ResourceManager.GetString("StartProcessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for input (1) ....
        /// </summary>
        public static string Step1Text {
            get {
                return ResourceManager.GetString("Step1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for output path (2) ....
        /// </summary>
        public static string Step2Text {
            get {
                return ResourceManager.GetString("Step2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse mods to download for this specific game..
        /// </summary>
        public static string Tooltip_Button_DownloadMods {
            get {
                return ResourceManager.GetString("Tooltip_Button_DownloadMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Mod Crates compatible with this game. They must be in the &quot;Mods&quot; folder near this application..
        /// </summary>
        public static string Tooltip_Button_ModCrates {
            get {
                return ResourceManager.GetString("Tooltip_Button_ModCrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Mod Menu of this specific game..
        /// </summary>
        public static string Tooltip_Button_ModMenu {
            get {
                return ResourceManager.GetString("Tooltip_Button_ModMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a tool menu for creating mods..
        /// </summary>
        public static string Tooltip_Button_ModTools {
            get {
                return ResourceManager.GetString("Tooltip_Button_ModTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize the seed below this button..
        /// </summary>
        public static string Tooltip_Button_RandomizeSeed {
            get {
                return ResourceManager.GetString("Tooltip_Button_RandomizeSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the game files from a folder instead of a ROM..
        /// </summary>
        public static string Tooltip_Checkbox_LoadFromFolder {
            get {
                return ResourceManager.GetString("Tooltip_Checkbox_LoadFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy resulting modded files to a folder. Not supported by PS1/PS2 emulators..
        /// </summary>
        public static string Tooltip_Checkbox_SaveToFolder {
            get {
                return ResourceManager.GetString("Tooltip_Checkbox_SaveToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this to visit the relevant website of this game&apos;s mod support..
        /// </summary>
        public static string Tooltip_Label_API {
            get {
                return ResourceManager.GetString("Tooltip_Label_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this to visit the website of this tool..
        /// </summary>
        public static string Tooltip_Label_Version {
            get {
                return ResourceManager.GetString("Tooltip_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The seed of all randomizers for this game..
        /// </summary>
        public static string Tooltip_Numeric_Seed {
            get {
                return ResourceManager.GetString("Tooltip_Numeric_Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Console.
        /// </summary>
        public static string UnknownConsole {
            get {
                return ResourceManager.GetString("UnknownConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Region.
        /// </summary>
        public static string UnknownRegion {
            get {
                return ResourceManager.GetString("UnknownRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Game.
        /// </summary>
        public static string UnsupportedGameTitle {
            get {
                return ResourceManager.GetString("UnsupportedGameTitle", resourceCulture);
            }
        }
    }
}
