using System.Collections.Generic;
using CrateModLoader.ModProperties;
using CrateModGames.GameSpecific.Rayman3;

namespace CrateModLoader.GameSpecific.CrashTS
{
    [ModCategory((int)ModProps.Galleries)]
    public static class Twins_Data_Textures_Galleries
    {

        public static ModProp_TextureFile Gallery_Boss01 = new ModProp_TextureFile(false, "Boss Gallery 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss02 = new ModProp_TextureFile(false, "Boss Gallery 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss03 = new ModProp_TextureFile(false, "Boss Gallery 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss04 = new ModProp_TextureFile(false, "Boss Gallery 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss05 = new ModProp_TextureFile(false, "Boss Gallery 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss06 = new ModProp_TextureFile(false, "Boss Gallery 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss07 = new ModProp_TextureFile(false, "Boss Gallery 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss08 = new ModProp_TextureFile(false, "Boss Gallery 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss09 = new ModProp_TextureFile(false, "Boss Gallery 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss10 = new ModProp_TextureFile(false, "Boss Gallery 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss11 = new ModProp_TextureFile(false, "Boss Gallery 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss12 = new ModProp_TextureFile(false, "Boss Gallery 12", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss13 = new ModProp_TextureFile(false, "Boss Gallery 13", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss14 = new ModProp_TextureFile(false, "Boss Gallery 14", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss15 = new ModProp_TextureFile(false, "Boss Gallery 15", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Boss16 = new ModProp_TextureFile(false, "Boss Gallery 16", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_Concept01 = new ModProp_TextureFile(false, "Concept Gallery 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept02 = new ModProp_TextureFile(false, "Concept Gallery 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept03 = new ModProp_TextureFile(false, "Concept Gallery 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept04 = new ModProp_TextureFile(false, "Concept Gallery 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept05 = new ModProp_TextureFile(false, "Concept Gallery 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept06 = new ModProp_TextureFile(false, "Concept Gallery 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept07 = new ModProp_TextureFile(false, "Concept Gallery 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept08 = new ModProp_TextureFile(false, "Concept Gallery 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept09 = new ModProp_TextureFile(false, "Concept Gallery 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept10 = new ModProp_TextureFile(false, "Concept Gallery 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept11 = new ModProp_TextureFile(false, "Concept Gallery 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept12 = new ModProp_TextureFile(false, "Concept Gallery 12", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept13 = new ModProp_TextureFile(false, "Concept Gallery 13", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept14 = new ModProp_TextureFile(false, "Concept Gallery 14", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept15 = new ModProp_TextureFile(false, "Concept Gallery 15", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept16 = new ModProp_TextureFile(false, "Concept Gallery 16", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept17 = new ModProp_TextureFile(false, "Concept Gallery 17", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept18 = new ModProp_TextureFile(false, "Concept Gallery 18", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept19 = new ModProp_TextureFile(false, "Concept Gallery 19", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept20 = new ModProp_TextureFile(false, "Concept Gallery 20", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept21 = new ModProp_TextureFile(false, "Concept Gallery 21", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept22 = new ModProp_TextureFile(false, "Concept Gallery 22", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept23 = new ModProp_TextureFile(false, "Concept Gallery 23", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept24 = new ModProp_TextureFile(false, "Concept Gallery 24", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept25 = new ModProp_TextureFile(false, "Concept Gallery 25", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept26 = new ModProp_TextureFile(false, "Concept Gallery 26", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept27 = new ModProp_TextureFile(false, "Concept Gallery 27", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept28 = new ModProp_TextureFile(false, "Concept Gallery 28", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept29 = new ModProp_TextureFile(false, "Concept Gallery 29", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept30 = new ModProp_TextureFile(false, "Concept Gallery 30", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept31 = new ModProp_TextureFile(false, "Concept Gallery 31", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Concept32 = new ModProp_TextureFile(false, "Concept Gallery 32", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_Enemy01 = new ModProp_TextureFile(false, "Enemy Gallery 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy02 = new ModProp_TextureFile(false, "Enemy Gallery 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy03 = new ModProp_TextureFile(false, "Enemy Gallery 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy04 = new ModProp_TextureFile(false, "Enemy Gallery 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy05 = new ModProp_TextureFile(false, "Enemy Gallery 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy06 = new ModProp_TextureFile(false, "Enemy Gallery 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy07 = new ModProp_TextureFile(false, "Enemy Gallery 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy08 = new ModProp_TextureFile(false, "Enemy Gallery 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy09 = new ModProp_TextureFile(false, "Enemy Gallery 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy10 = new ModProp_TextureFile(false, "Enemy Gallery 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy11 = new ModProp_TextureFile(false, "Enemy Gallery 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy12 = new ModProp_TextureFile(false, "Enemy Gallery 12", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy13 = new ModProp_TextureFile(false, "Enemy Gallery 13", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy14 = new ModProp_TextureFile(false, "Enemy Gallery 14", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy15 = new ModProp_TextureFile(false, "Enemy Gallery 15", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy16 = new ModProp_TextureFile(false, "Enemy Gallery 16", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy17 = new ModProp_TextureFile(false, "Enemy Gallery 17", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy18 = new ModProp_TextureFile(false, "Enemy Gallery 18", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy19 = new ModProp_TextureFile(false, "Enemy Gallery 19", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy20 = new ModProp_TextureFile(false, "Enemy Gallery 20", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy21 = new ModProp_TextureFile(false, "Enemy Gallery 21", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy22 = new ModProp_TextureFile(false, "Enemy Gallery 22", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy23 = new ModProp_TextureFile(false, "Enemy Gallery 23", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy24 = new ModProp_TextureFile(false, "Enemy Gallery 24", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy25 = new ModProp_TextureFile(false, "Enemy Gallery 25", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy26 = new ModProp_TextureFile(false, "Enemy Gallery 26", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy27 = new ModProp_TextureFile(false, "Enemy Gallery 27", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy28 = new ModProp_TextureFile(false, "Enemy Gallery 28", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy29 = new ModProp_TextureFile(false, "Enemy Gallery 29", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy30 = new ModProp_TextureFile(false, "Enemy Gallery 30", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy31 = new ModProp_TextureFile(false, "Enemy Gallery 31", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Enemy32 = new ModProp_TextureFile(false, "Enemy Gallery 32", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_Unseen01 = new ModProp_TextureFile(false, "Unseen Gallery 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen02 = new ModProp_TextureFile(false, "Unseen Gallery 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen03 = new ModProp_TextureFile(false, "Unseen Gallery 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen04 = new ModProp_TextureFile(false, "Unseen Gallery 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen05 = new ModProp_TextureFile(false, "Unseen Gallery 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen06 = new ModProp_TextureFile(false, "Unseen Gallery 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen07 = new ModProp_TextureFile(false, "Unseen Gallery 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen08 = new ModProp_TextureFile(false, "Unseen Gallery 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen09 = new ModProp_TextureFile(false, "Unseen Gallery 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen10 = new ModProp_TextureFile(false, "Unseen Gallery 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen11 = new ModProp_TextureFile(false, "Unseen Gallery 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen12 = new ModProp_TextureFile(false, "Unseen Gallery 12", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen13 = new ModProp_TextureFile(false, "Unseen Gallery 13", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen14 = new ModProp_TextureFile(false, "Unseen Gallery 14", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen15 = new ModProp_TextureFile(false, "Unseen Gallery 15", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen16 = new ModProp_TextureFile(false, "Unseen Gallery 16", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen17 = new ModProp_TextureFile(false, "Unseen Gallery 17", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen18 = new ModProp_TextureFile(false, "Unseen Gallery 18", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen19 = new ModProp_TextureFile(false, "Unseen Gallery 19", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen20 = new ModProp_TextureFile(false, "Unseen Gallery 20", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen21 = new ModProp_TextureFile(false, "Unseen Gallery 21", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen22 = new ModProp_TextureFile(false, "Unseen Gallery 22", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen23 = new ModProp_TextureFile(false, "Unseen Gallery 23", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen24 = new ModProp_TextureFile(false, "Unseen Gallery 24", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen25 = new ModProp_TextureFile(false, "Unseen Gallery 25", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen26 = new ModProp_TextureFile(false, "Unseen Gallery 26", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen27 = new ModProp_TextureFile(false, "Unseen Gallery 27", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen28 = new ModProp_TextureFile(false, "Unseen Gallery 28", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen29 = new ModProp_TextureFile(false, "Unseen Gallery 29", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen30 = new ModProp_TextureFile(false, "Unseen Gallery 30", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen31 = new ModProp_TextureFile(false, "Unseen Gallery 31", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen32 = new ModProp_TextureFile(false, "Unseen Gallery 32", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen33 = new ModProp_TextureFile(false, "Unseen Gallery 33", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen34 = new ModProp_TextureFile(false, "Unseen Gallery 34", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen35 = new ModProp_TextureFile(false, "Unseen Gallery 35", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen36 = new ModProp_TextureFile(false, "Unseen Gallery 36", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen37 = new ModProp_TextureFile(false, "Unseen Gallery 37", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen38 = new ModProp_TextureFile(false, "Unseen Gallery 38", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen39 = new ModProp_TextureFile(false, "Unseen Gallery 39", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen40 = new ModProp_TextureFile(false, "Unseen Gallery 40", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen41 = new ModProp_TextureFile(false, "Unseen Gallery 41", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen42 = new ModProp_TextureFile(false, "Unseen Gallery 42", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen43 = new ModProp_TextureFile(false, "Unseen Gallery 43", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen44 = new ModProp_TextureFile(false, "Unseen Gallery 44", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen45 = new ModProp_TextureFile(false, "Unseen Gallery 45", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen46 = new ModProp_TextureFile(false, "Unseen Gallery 46", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen47 = new ModProp_TextureFile(false, "Unseen Gallery 47", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_Unseen48 = new ModProp_TextureFile(false, "Unseen Gallery 48", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryNSanity01 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity02 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity03 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity04 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity05 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity06 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity07 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity08 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity09 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity10 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryNSanity11 = new ModProp_TextureFile(false, "Storyboard Gallery - N.Sanity Island 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryJungle01 = new ModProp_TextureFile(false, "Storyboard Gallery - Jungle Bungle 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryJungle02 = new ModProp_TextureFile(false, "Storyboard Gallery - Jungle Bungle 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryJungle03 = new ModProp_TextureFile(false, "Storyboard Gallery - Jungle Bungle 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryJungle04 = new ModProp_TextureFile(false, "Storyboard Gallery - Jungle Bungle 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryJungle05 = new ModProp_TextureFile(false, "Storyboard Gallery - Jungle Bungle 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryJungle06 = new ModProp_TextureFile(false, "Storyboard Gallery - Jungle Bungle 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryJungle07 = new ModProp_TextureFile(false, "Storyboard Gallery - Jungle Bungle 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryJungle08 = new ModProp_TextureFile(false, "Storyboard Gallery - Jungle Bungle 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryCavern01 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern02 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern03 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern04 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern05 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern06 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern07 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern08 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern09 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern10 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern11 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern12 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 12", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern13 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 13", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryCavern14 = new ModProp_TextureFile(false, "Storyboard Gallery - Cavern Catastrophe 14", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryTotem01 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem02 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem03 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem04 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem05 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem06 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem07 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem08 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem09 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem10 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem11 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem12 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 12", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem13 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 13", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem14 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 14", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTotem15 = new ModProp_TextureFile(false, "Storyboard Gallery - Totem Hokum 15", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryIceHub01 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub02 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub03 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub04 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub05 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub06 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub07 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub08 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub09 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub10 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub11 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub12 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 12", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub13 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 13", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub14 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 14", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceHub15 = new ModProp_TextureFile(false, "Storyboard Gallery - Iceberg Lab 15", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryIceClimb01 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb02 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb03 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb04 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb05 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb06 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb07 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb08 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb09 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb10 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb11 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb12 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 12", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb13 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 13", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb14 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 14", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb15 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 15", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb16 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 16", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryIceClimb17 = new ModProp_TextureFile(false, "Storyboard Gallery - Ice Climb 17", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StorySlip01 = new ModProp_TextureFile(false, "Storyboard Gallery - Slip Slide Icecapades 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StorySlip02 = new ModProp_TextureFile(false, "Storyboard Gallery - Slip Slide Icecapades 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StorySlip03 = new ModProp_TextureFile(false, "Storyboard Gallery - Slip Slide Icecapades 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StorySlip04 = new ModProp_TextureFile(false, "Storyboard Gallery - Slip Slide Icecapades 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StorySlip05 = new ModProp_TextureFile(false, "Storyboard Gallery - Slip Slide Icecapades 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StorySlip06 = new ModProp_TextureFile(false, "Storyboard Gallery - Slip Slide Icecapades 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StorySlip07 = new ModProp_TextureFile(false, "Storyboard Gallery - Slip Slide Icecapades 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StorySlip08 = new ModProp_TextureFile(false, "Storyboard Gallery - Slip Slide Icecapades 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StorySlip09 = new ModProp_TextureFile(false, "Storyboard Gallery - Slip Slide Icecapades 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryHighSeas01 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas02 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas03 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas04 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas05 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas06 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas07 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas08 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas09 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas10 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas11 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 11", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas12 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 12", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas13 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 13", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryHighSeas14 = new ModProp_TextureFile(false, "Storyboard Gallery - Hi Seas Hijinks 14", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryAcademy01 = new ModProp_TextureFile(false, "Storyboard Gallery - Academy of Evil 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAcademy02 = new ModProp_TextureFile(false, "Storyboard Gallery - Academy of Evil 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAcademy03 = new ModProp_TextureFile(false, "Storyboard Gallery - Academy of Evil 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAcademy04 = new ModProp_TextureFile(false, "Storyboard Gallery - Academy of Evil 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAcademy05 = new ModProp_TextureFile(false, "Storyboard Gallery - Academy of Evil 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAcademy06 = new ModProp_TextureFile(false, "Storyboard Gallery - Academy of Evil 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAcademy07 = new ModProp_TextureFile(false, "Storyboard Gallery - Academy of Evil 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAcademy08 = new ModProp_TextureFile(false, "Storyboard Gallery - Academy of Evil 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryBoiler01 = new ModProp_TextureFile(false, "Storyboard Gallery - Boiler Room Doom 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryBoiler02 = new ModProp_TextureFile(false, "Storyboard Gallery - Boiler Room Doom 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryBoiler03 = new ModProp_TextureFile(false, "Storyboard Gallery - Boiler Room Doom 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryBoiler04 = new ModProp_TextureFile(false, "Storyboard Gallery - Boiler Room Doom 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryBoiler05 = new ModProp_TextureFile(false, "Storyboard Gallery - Boiler Room Doom 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryBoiler06 = new ModProp_TextureFile(false, "Storyboard Gallery - Boiler Room Doom 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryBoiler07 = new ModProp_TextureFile(false, "Storyboard Gallery - Boiler Room Doom 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryClassroom01 = new ModProp_TextureFile(false, "Storyboard Gallery - Classroom Chaos 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryClassroom02 = new ModProp_TextureFile(false, "Storyboard Gallery - Classroom Chaos 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryClassroom03 = new ModProp_TextureFile(false, "Storyboard Gallery - Classroom Chaos 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryClassroom04 = new ModProp_TextureFile(false, "Storyboard Gallery - Classroom Chaos 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryClassroom05 = new ModProp_TextureFile(false, "Storyboard Gallery - Classroom Chaos 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryClassroom06 = new ModProp_TextureFile(false, "Storyboard Gallery - Classroom Chaos 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryClassroom07 = new ModProp_TextureFile(false, "Storyboard Gallery - Classroom Chaos 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryClassroom08 = new ModProp_TextureFile(false, "Storyboard Gallery - Classroom Chaos 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryClassroom09 = new ModProp_TextureFile(false, "Storyboard Gallery - Classroom Chaos 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryRooftop01 = new ModProp_TextureFile(false, "Storyboard Gallery - Rooftop Rampage 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRooftop02 = new ModProp_TextureFile(false, "Storyboard Gallery - Rooftop Rampage 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRooftop03 = new ModProp_TextureFile(false, "Storyboard Gallery - Rooftop Rampage 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRooftop04 = new ModProp_TextureFile(false, "Storyboard Gallery - Rooftop Rampage 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRooftop05 = new ModProp_TextureFile(false, "Storyboard Gallery - Rooftop Rampage 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRooftop06 = new ModProp_TextureFile(false, "Storyboard Gallery - Rooftop Rampage 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRooftop07 = new ModProp_TextureFile(false, "Storyboard Gallery - Rooftop Rampage 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryTwinsanity01 = new ModProp_TextureFile(false, "Storyboard Gallery - Twinsanity Island 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTwinsanity02 = new ModProp_TextureFile(false, "Storyboard Gallery - Twinsanity Island 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTwinsanity03 = new ModProp_TextureFile(false, "Storyboard Gallery - Twinsanity Island 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTwinsanity04 = new ModProp_TextureFile(false, "Storyboard Gallery - Twinsanity Island 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryTwinsanity05 = new ModProp_TextureFile(false, "Storyboard Gallery - Twinsanity Island 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryRockslide01 = new ModProp_TextureFile(false, "Storyboard Gallery - Rockslide Rumble 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRockslide02 = new ModProp_TextureFile(false, "Storyboard Gallery - Rockslide Rumble 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRockslide03 = new ModProp_TextureFile(false, "Storyboard Gallery - Rockslide Rumble 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRockslide04 = new ModProp_TextureFile(false, "Storyboard Gallery - Rockslide Rumble 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRockslide05 = new ModProp_TextureFile(false, "Storyboard Gallery - Rockslide Rumble 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryRockslide06 = new ModProp_TextureFile(false, "Storyboard Gallery - Rockslide Rumble 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryPursuit01 = new ModProp_TextureFile(false, "Storyboard Gallery - Bandicoot Pursuit 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryPursuit02 = new ModProp_TextureFile(false, "Storyboard Gallery - Bandicoot Pursuit 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryPursuit03 = new ModProp_TextureFile(false, "Storyboard Gallery - Bandicoot Pursuit 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryPursuit04 = new ModProp_TextureFile(false, "Storyboard Gallery - Bandicoot Pursuit 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryPursuit05 = new ModProp_TextureFile(false, "Storyboard Gallery - Bandicoot Pursuit 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryPursuit06 = new ModProp_TextureFile(false, "Storyboard Gallery - Bandicoot Pursuit 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

        public static ModProp_TextureFile Gallery_StoryAntAgony01 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 01", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAntAgony02 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 02", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAntAgony03 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 03", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAntAgony04 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 04", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAntAgony05 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 05", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAntAgony06 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 06", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAntAgony07 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 07", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAntAgony08 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 08", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAntAgony09 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 09", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };
        public static ModProp_TextureFile Gallery_StoryAntAgony10 = new ModProp_TextureFile(false, "Storyboard Gallery - Ant Agony 10", "")
        { AllowedConsoles = new List<ConsoleMode>() { ConsoleMode.PS2 }, };

    }
}
