//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrateModLoader.GameSpecific.CrashNitroKart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CNK_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CNK_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrateModLoader.GameSpecific.CrashNitroKart.CNK_Text", typeof(CNK_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools/API by BetaM, ManDude and eezstreet.
        /// </summary>
        internal static string API_Credit {
            get {
                return ResourceManager.GetString("API_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Nitro Kart.
        /// </summary>
        internal static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Fadeout/Flash Overlay.
        /// </summary>
        internal static string Mod_DisableFadeout {
            get {
                return ResourceManager.GetString("Mod_DisableFadeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the fadeout and flash overlay. Allows for certain major skips..
        /// </summary>
        internal static string Mod_DisableFadeoutDesc {
            get {
                return ResourceManager.GetString("Mod_DisableFadeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Unlock Popups.
        /// </summary>
        internal static string Mod_DisableUnlockPopups {
            get {
                return ResourceManager.GetString("Mod_DisableUnlockPopups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables unlock popups during Adventure mode..
        /// </summary>
        internal static string Mod_DisableUnlockPopupsDesc {
            get {
                return ResourceManager.GetString("Mod_DisableUnlockPopupsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Intro Videos.
        /// </summary>
        internal static string Mod_RemoveIntroVideos {
            get {
                return ResourceManager.GetString("Mod_RemoveIntroVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes intro videos before the main menu..
        /// </summary>
        internal static string Mod_RemoveIntroVideosDesc {
            get {
                return ResourceManager.GetString("Mod_RemoveIntroVideosDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Up Mask Hint Appearance.
        /// </summary>
        internal static string Mod_SpeedUpMaskHint {
            get {
                return ResourceManager.GetString("Mod_SpeedUpMaskHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeds up mask hints during Adventure mode..
        /// </summary>
        internal static string Mod_SpeedUpMaskHintDesc {
            get {
                return ResourceManager.GetString("Mod_SpeedUpMaskHintDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Adventure.
        /// </summary>
        internal static string Rand_Adventure {
            get {
                return ResourceManager.GetString("Rand_Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track, arena and boss entrances are shuffled around. Gem cup tracks are randomized. Final boss remains the same..
        /// </summary>
        internal static string Rand_AdventureDesc {
            get {
                return ResourceManager.GetString("Rand_AdventureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Character Stats.
        /// </summary>
        internal static string Rand_CharacterStats {
            get {
                return ResourceManager.GetString("Rand_CharacterStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizes each character&apos;s driving stats. The changes are accurately displayed in Adventure mode..
        /// </summary>
        internal static string Rand_CharacterStatsDesc {
            get {
                return ResourceManager.GetString("Rand_CharacterStatsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Drivers.
        /// </summary>
        internal static string Rand_Drivers {
            get {
                return ResourceManager.GetString("Rand_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizes models of each driver to be of another one..
        /// </summary>
        internal static string Rand_DriversDesc {
            get {
                return ResourceManager.GetString("Rand_DriversDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Karts.
        /// </summary>
        internal static string Rand_Karts {
            get {
                return ResourceManager.GetString("Rand_Karts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizes kart models of each team. (Boss karts not supported).
        /// </summary>
        internal static string Rand_KartsDesc {
            get {
                return ResourceManager.GetString("Rand_KartsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Kart Stats.
        /// </summary>
        internal static string Rand_KartStats {
            get {
                return ResourceManager.GetString("Rand_KartStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizes base kart stats. (the same for all characters).
        /// </summary>
        internal static string Rand_KartStatsDesc {
            get {
                return ResourceManager.GetString("Rand_KartStatsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Powerup Effects.
        /// </summary>
        internal static string Rand_PowerupEffects {
            get {
                return ResourceManager.GetString("Rand_PowerupEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizes visuals, speed and collision of certain powerups..
        /// </summary>
        internal static string Rand_PowerupEffectsDesc {
            get {
                return ResourceManager.GetString("Rand_PowerupEffectsDesc", resourceCulture);
            }
        }
    }
}
